"""fix_models_currency_and_relationships

Revision ID: ebce50ab179c
Revises: fab870b78f50
Create Date: 2026-09-12 12:02:03.541653

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebce50ab179c"
down_revision: Union[str, Sequence[str], None] = "fab870b78f50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "church",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("logo", sa.String(length=500), nullable=True),
        sa.Column("denomination", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_church_id"), "church", ["id"], unique=False)
    op.create_index(op.f("ix_church_slug"), "church", ["slug"], unique=True)
    op.create_table(
        "permission",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_id"), "permission", ["id"], unique=False)
    op.create_index(op.f("ix_permission_name"), "permission", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("profile_picture_url", sa.String(length=500), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                "PENDING",
                name="accountstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "verification",
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verification_id"), "verification", ["id"], unique=False)
    op.create_index(
        op.f("ix_verification_identifier"), "verification", ["identifier"], unique=False
    )
    op.create_table(
        "account",
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(length=2000), nullable=True),
        sa.Column("refresh_token", sa.String(length=2000), nullable=True),
        sa.Column("id_token", sa.String(length=2000), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_id"), "account", ["id"], unique=False)
    op.create_table(
        "admin_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_admin_details_id"), "admin_details", ["id"], unique=False)
    op.create_table(
        "announcement",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("author_id", sa.String(), nullable=True),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_announcement_id"), "announcement", ["id"], unique=False)
    op.create_table(
        "asset",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("purchase_date", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "MAINTENANCE",
                "DISPOSED",
                "SOLD",
                "DONATED",
                "LOST",
                "STOLEN",
                name="assetstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "condition",
            postgresql.ENUM(
                "EXCELLENT",
                "GOOD",
                "FAIR",
                "POOR",
                name="assetcondition",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_id"), "asset", ["id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=255), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("church_id", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_church_id"), "audit_log", ["church_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_id"), "audit_log", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False
    )
    op.create_table(
        "bishop_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("appointment_date", sa.DateTime(), nullable=True),
        sa.Column("jurisdiction_area", sa.String(length=255), nullable=True),
        sa.Column("biography", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_bishop_details_id"), "bishop_details", ["id"], unique=False
    )
    op.create_table(
        "branch",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branch_id"), "branch", ["id"], unique=False)
    op.create_table(
        "church_subscription",
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("BASIC", "MINISTRY", "CATHEDRAL", "CUSTOM", name="churchplan"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "EXPIRED",
                "CANCELED",
                "TRIAL",
                name="subscriptionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invoice_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("features", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("church_id"),
    )
    op.create_index(
        op.f("ix_church_subscription_id"), "church_subscription", ["id"], unique=False
    )
    op.create_table(
        "department",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_department_id"), "department", ["id"], unique=False)
    op.create_table(
        "emergency_contact",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=False),
        sa.Column("relationship_type", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_emergency_contact_id"), "emergency_contact", ["id"], unique=False
    )
    op.create_table(
        "event",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "COMPLETED",
                "CANCELLED",
                "POSTPONED",
                name="eventstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_id"), "event", ["id"], unique=False)
    op.create_table(
        "expense",
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expense_id"), "expense", ["id"], unique=False)
    op.create_table(
        "invitation",
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inviter_id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inviter_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitation_email"), "invitation", ["email"], unique=False)
    op.create_index(op.f("ix_invitation_id"), "invitation", ["id"], unique=False)
    op.create_table(
        "member_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("membership_date", sa.DateTime(), nullable=True),
        sa.Column("baptism_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_member_details_id"), "member_details", ["id"], unique=False
    )
    op.create_table(
        "offering",
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TITHE",
                "OFFERING",
                "BUILDING_FUND",
                "MISSIONS",
                "SPECIAL_GIVING",
                "SPECIAL_OFFERING",
                "THANKSGIVING",
                "PARTNERSHIP",
                "DONATION",
                "MISSION",
                "OTHER",
                name="offeringtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            postgresql.ENUM(
                "CASH",
                "M_PESA",
                "BANK_TRANSFER",
                "CHEQUE",
                "OTHER",
                "CARD",
                "ONLINE",
                name="paymentmethod",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offering_id"), "offering", ["id"], unique=False)
    op.create_table(
        "pastor_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("ordination_date", sa.DateTime(), nullable=True),
        sa.Column("sermon_count", sa.Integer(), nullable=False),
        sa.Column("biography", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_pastor_details_id"), "pastor_details", ["id"], unique=False
    )
    op.create_table(
        "pledge",
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "COMPLETED",
                "CANCELLED",
                "OVERDUE",
                name="pledgestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pledge_id"), "pledge", ["id"], unique=False)
    op.create_table(
        "prayer_request",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "ANSWERED", "CLOSED", name="prayerstatus", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prayer_request_id"), "prayer_request", ["id"], unique=False
    )
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("church_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=False)
    op.create_table(
        "staff_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_staff_details_id"), "staff_details", ["id"], unique=False)
    op.create_table(
        "user_session",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_session_id"), "user_session", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_session_refresh_token"),
        "user_session",
        ["refresh_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False
    )
    op.create_table(
        "user_subscription",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("plan", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "EXPIRED",
                "CANCELED",
                "TRIAL",
                name="subscriptionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_subscription_id"), "user_subscription", ["id"], unique=False
    )
    op.create_table(
        "visitor_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("visit_date", sa.DateTime(), nullable=False),
        sa.Column("how_did_you_hear", sa.String(length=50), nullable=False),
        sa.Column("follow_up_status", sa.String(length=50), nullable=False),
        sa.Column("follow_up_date", sa.DateTime(), nullable=True),
        sa.Column("follow_up_notes", sa.String(length=1000), nullable=True),
        sa.Column("interested_in_membership", sa.Boolean(), nullable=False),
        sa.Column("invited_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_visitor_details_id"), "visitor_details", ["id"], unique=False
    )
    op.create_table(
        "volunteer_details",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("hours_contributed", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_volunteer_details_id"), "volunteer_details", ["id"], unique=False
    )
    op.create_table(
        "activity",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_id"), "activity", ["id"], unique=False)
    op.create_table(
        "address",
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("zip_code", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("church_id", sa.String(), nullable=True),
        sa.Column("branch_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id"),
        sa.UniqueConstraint("church_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_address_id"), "address", ["id"], unique=False)
    op.create_table(
        "attendance",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PRESENT",
                "ABSENT",
                "LATE",
                "EXCUSED",
                name="attendancestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attendance_id"), "attendance", ["id"], unique=False)
    op.create_table(
        "availability_schedule",
        sa.Column("volunteer_details_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["volunteer_details_id"], ["volunteer_details.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volunteer_details_id"),
    )
    op.create_index(
        op.f("ix_availability_schedule_id"),
        "availability_schedule",
        ["id"],
        unique=False,
    )
    op.create_table(
        "background_check",
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_date", sa.DateTime(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column("clearance_level", sa.String(length=50), nullable=True),
        sa.Column("volunteer_details_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["volunteer_details_id"], ["volunteer_details.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volunteer_details_id"),
    )
    op.create_index(
        op.f("ix_background_check_id"), "background_check", ["id"], unique=False
    )
    op.create_table(
        "branch_member",
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branch_member_id"), "branch_member", ["id"], unique=False)
    op.create_table(
        "department_member",
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["department.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_department_member_id"), "department_member", ["id"], unique=False
    )
    op.create_table(
        "group",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("department_id", sa.String(), nullable=True),
        sa.Column("leader_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["department.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["leader_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_table(
        "maintenance_record",
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_record_id"), "maintenance_record", ["id"], unique=False
    )
    op.create_table(
        "member",
        sa.Column("church_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("roles", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("position", sa.String(length=255), nullable=True),
        sa.Column("branch_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_member_id"), "member", ["id"], unique=False)
    op.create_table(
        "pastor_assignment",
        sa.Column("position", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=True),
        sa.Column("pastor_details_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pastor_details_id"], ["pastor_details.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pastor_assignment_id"), "pastor_assignment", ["id"], unique=False
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("permission_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("church_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_role_id"), "user_role", ["id"], unique=False)
    op.create_table(
        "volunteer_role",
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("volunteer_details_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["volunteer_details_id"], ["volunteer_details.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_volunteer_role_id"), "volunteer_role", ["id"], unique=False
    )
    op.create_table(
        "group_member",
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_member_id"), "group_member", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_member_id"), table_name="group_member")
    op.drop_table("group_member")
    op.drop_index(op.f("ix_volunteer_role_id"), table_name="volunteer_role")
    op.drop_table("volunteer_role")
    op.drop_index(op.f("ix_user_role_id"), table_name="user_role")
    op.drop_table("user_role")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_pastor_assignment_id"), table_name="pastor_assignment")
    op.drop_table("pastor_assignment")
    op.drop_index(op.f("ix_member_id"), table_name="member")
    op.drop_table("member")
    op.drop_index(op.f("ix_maintenance_record_id"), table_name="maintenance_record")
    op.drop_table("maintenance_record")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_department_member_id"), table_name="department_member")
    op.drop_table("department_member")
    op.drop_index(op.f("ix_branch_member_id"), table_name="branch_member")
    op.drop_table("branch_member")
    op.drop_index(op.f("ix_background_check_id"), table_name="background_check")
    op.drop_table("background_check")
    op.drop_index(
        op.f("ix_availability_schedule_id"), table_name="availability_schedule"
    )
    op.drop_table("availability_schedule")
    op.drop_index(op.f("ix_attendance_id"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_address_id"), table_name="address")
    op.drop_table("address")
    op.drop_index(op.f("ix_activity_id"), table_name="activity")
    op.drop_table("activity")
    op.drop_index(op.f("ix_volunteer_details_id"), table_name="volunteer_details")
    op.drop_table("volunteer_details")
    op.drop_index(op.f("ix_visitor_details_id"), table_name="visitor_details")
    op.drop_table("visitor_details")
    op.drop_index(op.f("ix_user_subscription_id"), table_name="user_subscription")
    op.drop_table("user_subscription")
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_refresh_token"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_id"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_staff_details_id"), table_name="staff_details")
    op.drop_table("staff_details")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_prayer_request_id"), table_name="prayer_request")
    op.drop_table("prayer_request")
    op.drop_index(op.f("ix_pledge_id"), table_name="pledge")
    op.drop_table("pledge")
    op.drop_index(op.f("ix_pastor_details_id"), table_name="pastor_details")
    op.drop_table("pastor_details")
    op.drop_index(op.f("ix_offering_id"), table_name="offering")
    op.drop_table("offering")
    op.drop_index(op.f("ix_member_details_id"), table_name="member_details")
    op.drop_table("member_details")
    op.drop_index(op.f("ix_invitation_id"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_email"), table_name="invitation")
    op.drop_table("invitation")
    op.drop_index(op.f("ix_expense_id"), table_name="expense")
    op.drop_table("expense")
    op.drop_index(op.f("ix_event_id"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_emergency_contact_id"), table_name="emergency_contact")
    op.drop_table("emergency_contact")
    op.drop_index(op.f("ix_department_id"), table_name="department")
    op.drop_table("department")
    op.drop_index(op.f("ix_church_subscription_id"), table_name="church_subscription")
    op.drop_table("church_subscription")
    op.drop_index(op.f("ix_branch_id"), table_name="branch")
    op.drop_table("branch")
    op.drop_index(op.f("ix_bishop_details_id"), table_name="bishop_details")
    op.drop_table("bishop_details")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_church_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_asset_id"), table_name="asset")
    op.drop_table("asset")
    op.drop_index(op.f("ix_announcement_id"), table_name="announcement")
    op.drop_table("announcement")
    op.drop_index(op.f("ix_admin_details_id"), table_name="admin_details")
    op.drop_table("admin_details")
    op.drop_index(op.f("ix_account_id"), table_name="account")
    op.drop_table("account")
    op.drop_index(op.f("ix_verification_identifier"), table_name="verification")
    op.drop_index(op.f("ix_verification_id"), table_name="verification")
    op.drop_table("verification")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_permission_name"), table_name="permission")
    op.drop_index(op.f("ix_permission_id"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_church_slug"), table_name="church")
    op.drop_index(op.f("ix_church_id"), table_name="church")
    op.drop_table("church")
    # ### end Alembic commands ###
