from app.models.audit import AuditLog
from app.models.auth import Permission, Role, UserRole, role_permission
from app.models.church import Church, Branch
from app.models.detail import (
    MemberDetails,
    PastorDetails,
    StaffDetails,
    VolunteerDetails,
)
from app.models.event import Activity, Attendance, Event
from app.models.finance import Expense, Offering, Pledge
from app.models.group import Department, DepartmentMember, Group, GroupMember
from app.models.member import Member, BranchMember
from app.models.operation import Announcement, Asset, MaintenanceRecord, PrayerRequest
from app.models.subscription import ChurchSubscription, UserSubscription
from app.models.user import User

# This file is used to import all models so that Alembic can detect them.

from app.enums import (  # noqa: F401
    Gender,
    MaritalStatus,
    AccountStatus,
    GlobalRole,
    ChurchRole,
    MembershipStatus,
    PastorAssignmentStatus,
    EmploymentType,
    VolunteerStatus,
    ClearanceLevel,
    AdminAccessLevel,
    HowDidYouHear,
    FollowUpStatus,
    DepartmentCategory,
    ExpenseCategory,
    ActivityType,
    GoalStatus,
    MemberRole,
    GroupCategory,
    GroupActivityType,
    GroupGoalStatus,
    EventStatus,
    OfferingType,
    PaymentMethod,
    PledgePurpose,
    PaymentSchedule,
    PledgeStatus,
    PrayerCategory,
    Priority,
    PrayerStatus,
    DayOfWeek,
    ServiceType,
    AssetStatus,
    AnnouncementTarget,
    AttendanceStatus,
    PaymentStatus,
    ReportType,
    MessageStatus,
    ContentCategory,
    ContentStatus,
    ContentType,
    DiscipleLevel,
    DiscipleStatus,
    ProgressStatus,
    MessageType,
    TemplateCategory,
    ScheduleType,
    ChurchPlan,
    MaintenanceSchedule,
    AssetCondition,
    AssetType,
    ActivityTypeEnum,
    ActivityStatus,
    UserPlan,
    SubscriptionStatus,
    PaymentMethodType,
    DateRange,
    ReportFormat,
    ReportStatus,
    RecipientType,
    TargetModel,
    AnnouncementCategory,
    AnnouncementStatus,
    LogLevel,
    LogSource,
    Environment,
    MilestoneCategory,
)

__all__ = [
    # Models
    "User",
    "Role",
    "Permission",
    "UserRole",
    # Association tables
    "role_permission",
    # Others
    "Church",
    "Branch",
    "Member",
    "BranchMember",
    "Department",
    "DepartmentMember",
    "Group",
    "GroupMember",
    "Event",
    "Activity",
    "Attendance",
    "Offering",
    "Pledge",
    "Expense",
    "Asset",
    "MaintenanceRecord",
    "Announcement",
    "PrayerRequest",
    "ChurchSubscription",
    "UserSubscription",
    "MemberDetails",
    "PastorDetails",
    "StaffDetails",
    "VolunteerDetails",
    "AuditLog",
    # Enums
    "Gender",
    "MaritalStatus",
    "AccountStatus",
    "GlobalRole",
    "ChurchRole",
    "MembershipStatus",
    "PastorAssignmentStatus",
    "EmploymentType",
    "VolunteerStatus",
    "ClearanceLevel",
    "AdminAccessLevel",
    "HowDidYouHear",
    "FollowUpStatus",
    "DepartmentCategory",
    "ExpenseCategory",
    "ActivityType",
    "GoalStatus",
    "MemberRole",
    "GroupCategory",
    "GroupActivityType",
    "GroupGoalStatus",
    "EventStatus",
    "OfferingType",
    "PaymentMethod",
    "PledgePurpose",
    "PaymentSchedule",
    "PledgeStatus",
    "PrayerCategory",
    "Priority",
    "PrayerStatus",
    "DayOfWeek",
    "ServiceType",
    "AssetStatus",
    "AnnouncementTarget",
    "AttendanceStatus",
    "PaymentStatus",
    "ReportType",
    "MessageStatus",
    "ContentCategory",
    "ContentStatus",
    "ContentType",
    "DiscipleLevel",
    "DiscipleStatus",
    "ProgressStatus",
    "MessageType",
    "TemplateCategory",
    "ScheduleType",
    "ChurchPlan",
    "MaintenanceSchedule",
    "AssetCondition",
    "AssetType",
    "ActivityTypeEnum",
    "ActivityStatus",
    "UserPlan",
    "SubscriptionStatus",
    "PaymentMethodType",
    "DateRange",
    "ReportFormat",
    "ReportStatus",
    "RecipientType",
    "TargetModel",
    "AnnouncementCategory",
    "AnnouncementStatus",
    "LogLevel",
    "LogSource",
    "Environment",
    "MilestoneCategory",
]
